apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - target:
      kind: Deployment
      name: image-reflector-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--aws-autologin-for-ecr=true"
