extensions:
  health_check:

receivers:
#  otlp:
#    protocols:
#      grpc:
#        endpoint: 0.0.0.0:4317
#      http:
#        endpoint: 0.0.0.0:55681
  prometheus:
    config:
      global:
        evaluation_interval: 30s
      scrape_configs:
        - job_name: prod/task-service
          static_configs:
            - targets: ['localhost:3000']
#          kubernetes_sd_configs:
#            - role: endpoints
#              namespaces:
#                names:
#                  - prod
          scrape_interval: 30s
          metrics_path: /metrics
#          relabel_configs:
#            - source_labels:
#                - job
#              target_label: __tmp_prometheus_job_name
#            - action: keep
#              source_labels:
#                - __meta_kubernetes_service_label_app_kubernetes_io_name
#                - __meta_kubernetes_service_labelpresent_app_kubernetes_io_name
#              regex: (task-tool);true
#            - action: keep
#              source_labels:
#                - __meta_kubernetes_pod_container_port_name
#              regex: http
#            - source_labels:
#                - __meta_kubernetes_endpoint_address_target_kind
#                - __meta_kubernetes_endpoint_address_target_name
#              separator: ;
#              regex: Node;(.*)
#              replacement: ${1}
#              target_label: node
#            - source_labels:
#                - __meta_kubernetes_endpoint_address_target_kind
#                - __meta_kubernetes_endpoint_address_target_name
#              separator: ;
#              regex: Pod;(.*)
#              replacement: ${1}
#              target_label: pod
#            - source_labels:
#                - __meta_kubernetes_namespace
#              target_label: namespace
#            - source_labels:
#                - __meta_kubernetes_service_name
#              target_label: service
#            - source_labels:
#                - __meta_kubernetes_pod_name
#              target_label: pod
#            - source_labels:
#                - __meta_kubernetes_pod_container_name
#              target_label: container
#            - source_labels:
#                - __meta_kubernetes_service_name
#              target_label: job
#              replacement: ${1}
#            - target_label: endpoint
#              replacement: http
#            - source_labels:
#                - __address__
#              target_label: __tmp_hash
#              modulus: 1
#              action: hashmod
#            - source_labels:
#                - __tmp_hash
#              regex: 0
#              action: keep

processors:
#  batch/traces:
#    timeout: 1s
#    send_batch_size: 50
  batch/metrics:
    timeout: 60s

exporters:
#  awsxray:

  # AWS Embedded metric format
  # AWS Doc: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html
  # Exporter Doc: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awsemfexporter
  awsemf:

service:
  pipelines:
#    traces:
#      receivers: [otlp]
#      processors: [batch/traces]
#      exporters: [awsxray]
    metrics:
      receivers: [prometheus]
      processors: [batch/metrics]
      exporters: [awsemf]
