commonLabels:
  env: prod

namespace: prod
namePrefix: prod-

resources:
  - ../../base
  - task-web/deployment.yaml
  - task-web/service.yaml
  - lets-encrypt-issuer.template.yaml

patches:
  - path: patches/task-service/deployment.patch.yaml
  - path: patches/task-reporter/cronjob.patch.yaml
  - target:
      kind: Ingress
      name: app-ingress
    path: patches/ingress/ingress.patch.yaml

configMapGenerator:
  - name: task-service-config
    behavior: merge
    envs:
      - patches/task-service/.env
  - name: task-reporter-config
    behavior: merge
    envs:
      - patches/task-reporter/.env

images:
  - name: task-service
    newName: 446197467950.dkr.ecr.ap-northeast-1.amazonaws.com/mamezou-tech/task-service
    newTag: 1.0.0
  - name: task-reporter
    newName: 446197467950.dkr.ecr.ap-northeast-1.amazonaws.com/mamezou-tech/task-reporter
    newTag: 1.0.0
  - name: task-web
    newName: 446197467950.dkr.ecr.ap-northeast-1.amazonaws.com/mamezou-tech/task-web
    newTag: 1.0.0
