apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
  namespace: prod
spec:
  acme:
    # Let's Encryptの証明書発行URL(練習用)
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    # こっちが本番向け(Trustedな証明書)
    server: https://acme-v02.api.letsencrypt.org/directory
    # Let's Encryptに登録するアドレス
    email: '<your-mail-address>'
    # Let's Encryptへのアクセス用のクレデンシャル(Cert Managerが自動生成する)
    privateKeySecretRef:
      name: acme-client-letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
