kind: Deployment
apiVersion: apps/v1
metadata:
  name: ap-northeast-1a-app
  labels:
    app: ap-northeast-1a-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ap-northeast-1a-app
  template:
    metadata:
      name: ap-northeast-1a-app
      labels:
        app: ap-northeast-1a-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - ap-northeast-1a
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - m5.large
                      - m5.xlarge
                      - m5.2xlarge
              weight: 100
      containers:
        - name: ap-northeast-1a-app
          image: alpine:latest
          command: [sh, -c, "sleep infinity"]
          resources:
            requests:
              # 検証のため1Node2台配置できるサイズで割当
              cpu: 800m
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ap-northeast-1c-app
  labels:
    app: ap-northeast-1c-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ap-northeast-1c-app
  template:
    metadata:
      name: ap-northeast-1c-app
      labels:
        app: ap-northeast-1c-app
    spec:
#      nodeSelector:
#        topology.kubernetes.io/zone: ap-northeast-1c
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - ap-northeast-1c
      containers:
        - name: ap-northeast-1c-app
          image: alpine:latest
          command: [sh, -c, "sleep infinity"]
