- op: add
  path: /metadata/annotations
  value:
    external-dns.alpha.kubernetes.io/hostname: task.mamezou-tech.com
    cert-manager.io/issuer: "prod-letsencrypt-issuer"
    cert-manager.io/renew-before: 2158h
- op: add
  path: /spec/tls
  value:
    - hosts:
        - task.mamezou-tech.com
      secretName: letsencrypt-cert
- op: replace
  path: /spec/rules/0/host
  value: task.mamezou-tech.com
- op: add
  path: /spec/rules/0/http/paths/-
  value:
    backend:
      service:
        name: task-web
        port:
          number: 8080
    path: /
    pathType: Prefix
