apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-web
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-web
  template:
    metadata:
      labels:
        app: task-web
    spec:
      containers:
        - name: task-web
          image: task-web
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /
          livenessProbe:
            httpGet:
              port: 8080
              path: /
