apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-init-scripts-config
data:
  # AWS Credential情報初期化
  01-credential.sh: |
    #!/bin/bash
    aws configure set aws_access_key_id localstack
    aws configure set aws_secret_access_key localstack
    aws configure set region local
    export LOCALSTACK_ENDPOINT=http://localhost:4566
  # DynamoDBテーブル作成
  02-create-task-table.sh: |
    #!/bin/bash
    aws dynamodb create-table --table-name tasks \
      --key-schema AttributeName=task_id,KeyType=HASH \
      --attribute-definitions file:///docker-entrypoint-initaws.d/02-task-attr-definitions.json \
      --global-secondary-indexes file:///docker-entrypoint-initaws.d/02-task-gsi.json \
      --billing-mode PAY_PER_REQUEST \
      --endpoint ${LOCALSTACK_ENDPOINT}
    aws dynamodb list-tables --endpoint ${LOCALSTACK_ENDPOINT} --region local
  02-task-attr-definitions.json: |
    [
      {
        "AttributeName": "task_id",
        "AttributeType": "S"
      },
      {
        "AttributeName": "start_at",
        "AttributeType": "N"
      },
      {
        "AttributeName": "updated_at",
        "AttributeType": "N"
      },
      {
        "AttributeName": "user_name",
        "AttributeType": "S"
      },
      {
        "AttributeName": "status",
        "AttributeType": "S"
      }
    ]
  02-task-gsi.json: |
    [
      {
        "IndexName": "user_index",
        "KeySchema": [
          {
             "AttributeName": "user_name",
             "KeyType": "HASH"
          },
          {
             "AttributeName": "start_at",
             "KeyType": "RANGE"
          }
        ],
        "Projection": {
            "ProjectionType": "ALL"
        }
      },
      {
        "IndexName": "status_index",
        "KeySchema": [
          {
             "AttributeName": "status",
             "KeyType": "HASH"
          },
          {
             "AttributeName": "updated_at",
             "KeyType": "RANGE"
          }
        ],
        "Projection": {
            "ProjectionType": "ALL"
        }
      }
    ]
  # S3バケット作成
  03-create-bucket.sh: |
    #!/bin/bash
    aws s3api create-bucket --bucket completed-task-report-bucket --endpoint ${LOCALSTACK_ENDPOINT}
    aws s3api list-buckets --endpoint ${LOCALSTACK_ENDPOINT}
