apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: sample
build:
  artifacts:
  - image: sample-app
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - app.yaml
    - ingress.patch.yaml
